### ISSUE TITLE
gun control

### ISSUE THREAD

**Issue by shawngraham** [Ottawagunner/ResearchHistoryNotes#1]
Ok: but this is pretty recent history, as it were... I mean, how about looking at the ways people discuss past wars on twitter, reddit? Then you'd be getting a public history angle...

**Comment by Ottawagunner** [comment]
I think I want to search through Reddit with a list of historical figures and collecting the comment. Then analyse the context and look at how people talk about history, particularly figures. How does this sound.

**Comment by shawngraham** [comment]
yep - as per comments in class.
